apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whereami
  template:
    metadata:
      labels:
        app: whereami
    spec:
      containers:
      - name: nginx
        image: nginx: latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 500Mi
            cpu: "250m"
          limits:
            memory: 1Gi
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx
spec:
  hosts:
    - "mci-test.preprod.n.svc.tv.telus.net"
  gateways:
    - "gateway-public"
  http:
  - route:
    - destination:
        host: nginx
        port:
          number: 80
