apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami
  labels:
    app: whereami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whereami
  template:
    metadata:
      labels:
        app: whereami
    spec:
      containers:
      - name: whereami
        image: us-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.7
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 500Mi
            cpu: "250m"
          limits:
            memory: 1Gi
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: whereami
spec:
  selector:
    app: whereami
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: whereami-mcs
spec:
  template:
    spec:
      selector:
        app: whereami
      ports:
      - name: web
        protocol: TCP
        port: 8080
        targetPort: 80
